{{- if .Values.httpListenerKeys.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.httpListenerKeys.secretName | default "http-listener-keys" }}
  labels:
    {{- include "kumomta.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $username, $password := .Values.httpListenerKeys.users }}
  {{ $username }}: {{ $password | b64enc }}
{{- end }}
{{- end }}
