{{- if .Values.secrets.httpListener.create }}
apiVersion: v1
kind: Secret
metadata:
  name: http-listener-keys
  labels:
    {{- include "kumomta.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.httpListener.keys }}
  {{- range $key, $value := .Values.secrets.httpListener.keys }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- else }}
  # Default API user - CHANGE THIS IN PRODUCTION!
  # To generate a secure password: openssl rand -hex 16
  # Password is stored as plain text in values, will be base64 encoded here
  api-user: {{ .Values.secrets.httpListener.defaultPassword | default "dfad6143b4520f8526e4f9a0b25ab42b" | b64enc }}
  {{- end }}
{{- end }}
