{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kumomta.fullname" . }}
  labels:
    {{- include "kumomta.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - path: /metrics
      targetPort: {{ .Values.serviceMonitor.targetPort | default "http" }}
      {{- with .Values.serviceMonitor.basicAuth }}
      basicAuth:
      {{- toYaml . | nindent 8 }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "kumomta.selectorLabels" . | nindent 6 }}
{{- end }}
